11

diff --git a/.github/workflows/tf_CICD.yaml b/.github/workflows/tf_CICD.yaml
--- a/.github/workflows/tf_CICD.yaml
+++ b/.github/workflows/tf_CICD.yaml
@@ -24,10 +24,15 @@ jobs:
   deploy:
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v3
+      - name: Checkout Repository
+        uses: actions/checkout@v3
+        with:
+          fetch-depth: 0
 
       - name: Debug Directory Structure
-        run: ls -R
+        run: |
+          pwd
+          ls -R
 
       - name: Setup Terraform
         uses: hashicorp/setup-terraform@v2
@@ -39,17 +44,17 @@ jobs:
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: ${{ github.event.inputs.region }}
 
-      - name: Terraform Init
-        run: terraform init -reconfigure
-        working-directory: ./tf
-
       - name: Set Terraform Variables File
         run: echo "TFVARS_FILE=region.${{ github.event.inputs.region }}.${{ github.event.inputs.environment }}.tfvars" >> $GITHUB_ENV
 
       - name: Debug Terraform Variables File
         run: |
           echo "Using tfvars file: $TFVARS_FILE"
-          ls -l ./tf
+          ls -l ./tf || echo "tf directory not found!"
+        working-directory: ./tf || true
+
+      - name: Terraform Init
+        run: terraform init -reconfigure
         working-directory: ./tf
 
       - name: Terraform Plan
